-- MetroClima · esquema productivo para Supabase
-- Los correos autorizados se cargan directamente en Supabase y nunca se
-- publican en el repositorio.

create extension if not exists "pgcrypto";
create schema if not exists private;

create type public.rol_metroclima as enum ('administrador');
create type public.estado_consulta as enum ('pendiente', 'en_seguimiento', 'respondida', 'presupuestada', 'archivada');
create type public.estado_presupuesto as enum ('borrador', 'enviado', 'aceptado', 'rechazado', 'vencido');

create table public.admin_emails_permitidos (
  email text primary key check (email = lower(email)),
  nombre text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  rol public.rol_metroclima not null default 'administrador',
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table public.consultas (
  id uuid primary key default gen_random_uuid(),
  categoria text not null,
  titulo text not null check (char_length(titulo) between 8 and 140),
  consulta text not null check (char_length(consulta) between 20 and 3000),
  nombre_publico text not null default 'Consulta anónima',
  acepta_contacto boolean not null default false,
  email text,
  telefono text,
  localidad text,
  estado public.estado_consulta not null default 'pendiente',
  visible_publicamente boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  check (acepta_contacto or (email is null and telefono is null and localidad is null))
);

create table public.respuestas (
  id uuid primary key default gen_random_uuid(),
  consulta_id uuid not null references public.consultas(id) on delete cascade,
  autor_id uuid not null references public.perfiles(id),
  respuesta text not null check (char_length(respuesta) between 3 and 5000),
  publica boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.clientes (
  id uuid primary key default gen_random_uuid(),
  tipo text not null default 'persona' check (tipo in ('persona', 'empresa')),
  nombre_razon_social text not null,
  cuit_dni text,
  condicion_iva text,
  email text,
  telefono text,
  direccion text,
  localidad text,
  observaciones text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.materiales (
  id uuid primary key default gen_random_uuid(),
  codigo text unique,
  nombre text not null,
  unidad text not null,
  costo_referencia numeric(14,2) not null default 0 check (costo_referencia >= 0),
  controla_stock boolean not null default false,
  stock_actual numeric(14,3),
  stock_minimo numeric(14,3),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.presupuestos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid references public.clientes(id),
  titulo text not null,
  descripcion text,
  tratamiento_fiscal text not null default 'monotributo_iva_no_discriminado',
  subtotal_mano_obra numeric(14,2) not null default 0 check (subtotal_mano_obra >= 0),
  subtotal_materiales numeric(14,2) not null default 0 check (subtotal_materiales >= 0),
  iva numeric(14,2) not null default 0 check (iva >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  validez_dias integer not null default 15 check (validez_dias between 1 and 365),
  condiciones_pago text not null default 'Efectivo, transferencia bancaria o Mercado Pago',
  garantia text not null default 'Todos nuestros trabajos cuentan con garantía.',
  estado public.estado_presupuesto not null default 'borrador',
  creado_por uuid not null references public.perfiles(id),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.items_presupuesto (
  id uuid primary key default gen_random_uuid(),
  presupuesto_id uuid not null references public.presupuestos(id) on delete cascade,
  tipo text not null check (tipo in ('mano_obra', 'material')),
  descripcion text not null,
  cantidad numeric(14,3) not null default 1 check (cantidad > 0),
  precio_unitario numeric(14,2) not null default 0 check (precio_unitario >= 0),
  total numeric(14,2) generated always as (cantidad * precio_unitario) stored,
  material_id uuid references public.materiales(id),
  orden integer not null default 0
);

create table public.comprobantes (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid references public.clientes(id),
  presupuesto_id uuid references public.presupuestos(id),
  responsable_id uuid not null references public.perfiles(id),
  tipo text not null default 'Factura C',
  punto_venta integer,
  numero bigint,
  cae text,
  cae_vencimiento date,
  total numeric(14,2) not null check (total >= 0),
  estado text not null default 'borrador',
  respuesta_arca jsonb,
  emitido_en timestamptz,
  creado_en timestamptz not null default now()
);

create or replace function private.actualizar_fecha_modificacion()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

create trigger consultas_actualizado_en before update on public.consultas
for each row execute function private.actualizar_fecha_modificacion();
create trigger respuestas_actualizado_en before update on public.respuestas
for each row execute function private.actualizar_fecha_modificacion();
create trigger clientes_actualizado_en before update on public.clientes
for each row execute function private.actualizar_fecha_modificacion();
create trigger materiales_actualizado_en before update on public.materiales
for each row execute function private.actualizar_fecha_modificacion();
create trigger presupuestos_actualizado_en before update on public.presupuestos
for each row execute function private.actualizar_fecha_modificacion();

create or replace function private.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.perfiles
    where id = auth.uid() and activo = true and rol = 'administrador'
  );
$$;

create or replace function private.vincular_admin_permitido()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  nombre_permitido text;
begin
  select nombre into nombre_permitido
  from public.admin_emails_permitidos
  where email = lower(new.email) and activo = true;

  if nombre_permitido is not null then
    insert into public.perfiles (id, nombre)
    values (new.id, nombre_permitido)
    on conflict (id) do update set nombre = excluded.nombre, activo = true;
  end if;

  return new;
end;
$$;

create trigger vincular_admin_al_crear_usuario
after insert or update of email on auth.users
for each row execute function private.vincular_admin_permitido();

revoke all on function private.es_admin() from public, anon;
revoke all on function private.vincular_admin_permitido() from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.es_admin() to authenticated;

alter table public.admin_emails_permitidos enable row level security;
alter table public.perfiles enable row level security;
alter table public.consultas enable row level security;
alter table public.respuestas enable row level security;
alter table public.clientes enable row level security;
alter table public.materiales enable row level security;
alter table public.presupuestos enable row level security;
alter table public.items_presupuesto enable row level security;
alter table public.comprobantes enable row level security;

revoke all on public.consultas from anon;
revoke all on public.admin_emails_permitidos from anon;
revoke all on public.perfiles from anon;
revoke all on public.respuestas from anon;
revoke all on public.clientes from anon;
revoke all on public.materiales from anon;
revoke all on public.presupuestos from anon;
revoke all on public.items_presupuesto from anon;
revoke all on public.comprobantes from anon;
grant insert (categoria, titulo, consulta, nombre_publico, acepta_contacto, email, telefono, localidad)
on public.consultas to anon;
grant select (id, categoria, titulo, consulta, nombre_publico, creado_en)
on public.consultas to anon;
grant select on public.respuestas to anon;

create policy "publico puede crear consultas"
on public.consultas for insert
to anon
with check (estado = 'pendiente' and visible_publicamente = true);

create policy "publico ve consultas publicas"
on public.consultas for select
to anon
using (visible_publicamente = true and estado <> 'archivada');

create policy "administradores gestionan consultas"
on public.consultas for all
to authenticated
using (private.es_admin())
with check (private.es_admin());

create policy "publico ve respuestas publicas"
on public.respuestas for select
to anon
using (publica = true);

create policy "administradores gestionan respuestas"
on public.respuestas for all
to authenticated
using (private.es_admin())
with check (private.es_admin());

create policy "administradores gestionan perfiles"
on public.perfiles for all
to authenticated
using (private.es_admin())
with check (private.es_admin());

create policy "administradores gestionan correos permitidos"
on public.admin_emails_permitidos for all
to authenticated
using (private.es_admin())
with check (private.es_admin());

create policy "administradores gestionan clientes"
on public.clientes for all to authenticated
using (private.es_admin()) with check (private.es_admin());

create policy "administradores gestionan materiales"
on public.materiales for all to authenticated
using (private.es_admin()) with check (private.es_admin());

create policy "administradores gestionan presupuestos"
on public.presupuestos for all to authenticated
using (private.es_admin()) with check (private.es_admin());

create policy "administradores gestionan items de presupuesto"
on public.items_presupuesto for all to authenticated
using (private.es_admin()) with check (private.es_admin());

create policy "administradores gestionan comprobantes"
on public.comprobantes for all to authenticated
using (private.es_admin()) with check (private.es_admin());

-- Vista pública deliberadamente limitada: no incluye correo, teléfono,
-- localidad, estado interno ni identificadores del administrador.
create or replace view public.consultas_publicas
with (security_barrier = true, security_invoker = true)
as
select
  c.id,
  c.categoria,
  c.titulo,
  c.consulta,
  c.nombre_publico,
  c.creado_en,
  (
    select r.respuesta
    from public.respuestas r
    where r.consulta_id = c.id and r.publica = true
    order by r.creado_en desc
    limit 1
  ) as respuesta
from public.consultas c
where c.visible_publicamente = true
  and c.estado <> 'archivada';

revoke all on public.consultas_publicas from public;
grant select on public.consultas_publicas to anon, authenticated;

create index consultas_estado_creado_idx on public.consultas (estado, creado_en desc);
create index respuestas_consulta_idx on public.respuestas (consulta_id, creado_en desc);
create index presupuestos_cliente_idx on public.presupuestos (cliente_id, creado_en desc);
create index comprobantes_cliente_idx on public.comprobantes (cliente_id, creado_en desc);
create index materiales_activo_nombre_idx on public.materiales (activo, nombre);
create index respuestas_autor_idx on public.respuestas (autor_id);
create index items_presupuesto_presupuesto_idx on public.items_presupuesto (presupuesto_id);
create index items_presupuesto_material_idx on public.items_presupuesto (material_id);
create index presupuestos_creado_por_idx on public.presupuestos (creado_por);
create index comprobantes_presupuesto_idx on public.comprobantes (presupuesto_id);
create index comprobantes_responsable_idx on public.comprobantes (responsable_id);

-- Cargar cada correo de administrador de forma privada en Supabase:
-- insert into public.admin_emails_permitidos (email, nombre)
-- values (lower('correo@privado.com'), 'Nombre');
