"use client";
import { useEffect,useMemo,useState } from "react";
import { getSupabaseBrowserClient,hasSupabaseConfig } from "@/lib/supabase/client";
type Rubro="todos"|"climatizacion"|"electricidad"; type Img={id:string;trabajo_id:string;storage_path:string;orden:number;alt:string;url:string}; type Review={presupuesto_id:string;nombre_publico:string;puntuacion:number;comentario:string}; type Work={id:string;presupuesto_id:string;titulo_publico:string;resumen:string;localidad_publica:string|null;fecha_realizacion:string|null;destacado:boolean;rubro:"climatizacion"|"electricidad";images:Img[];review?:Review};
export function PortfolioShowcase({initialFilter="todos",showFilters=false,limit}:{initialFilter?:Rubro;showFilters?:boolean;limit?:number}){
 const [works,setWorks]=useState<Work[]>([]),[filter,setFilter]=useState<Rubro>(initialFilter),[loading,setLoading]=useState(hasSupabaseConfig),[openWork,setOpenWork]=useState<Work|null>(null),[active,setActive]=useState(0);
 useEffect(()=>{const s=getSupabaseBrowserClient();if(!s)return;let mounted=true;(async()=>{const {data:rows,error}=await s.from("trabajos").select("id,presupuesto_id,titulo_publico,resumen,localidad_publica,fecha_realizacion,destacado,rubro").eq("publicado",true).order("destacado",{ascending:false}).order("fecha_realizacion",{ascending:false});if(error||!rows?.length){if(mounted){setWorks([]);setLoading(false)}return}const ids=rows.map((w:any)=>w.id),bids=rows.map((w:any)=>w.presupuesto_id);const [ir,rr]=await Promise.all([s.from("trabajo_imagenes").select("id,trabajo_id,storage_path,orden,alt").in("trabajo_id",ids).order("orden"),s.from("resenas_clientes").select("presupuesto_id,nombre_publico,puntuacion,comentario").in("presupuesto_id",bids).eq("aprobada",true)]);const imgs=ir.data??[],reviews=(rr.data??[]) as Review[];const out=rows.map((w:any)=>({...w,images:imgs.filter((i:any)=>i.trabajo_id===w.id).slice(0,20).map((i:any)=>({...i,url:s.storage.from("trabajos").getPublicUrl(i.storage_path).data.publicUrl})),review:reviews.find(r=>r.presupuesto_id===w.presupuesto_id)}));if(mounted){setWorks(out as Work[]);setLoading(false)}})();return()=>{mounted=false}},[]);
 useEffect(()=>{document.body.style.overflow=openWork?"hidden":"";return()=>{document.body.style.overflow=""}},[openWork]);
 const filtered=useMemo(()=>{const r=filter==="todos"?works:works.filter(w=>w.rubro===filter);return typeof limit==="number"?r.slice(0,limit):r},[works,filter,limit]);const open=(w:Work)=>{setOpenWork(w);setActive(0)};const move=(n:number)=>{if(openWork?.images.length)setActive(v=>(v+n+openWork.images.length)%openWork.images.length)};
 return <>{showFilters&&<div className="portfolio-filters">{([["todos","Todos"],["climatizacion","Climatización"],["electricidad","Electricidad"]] as [Rubro,string][]).map(([v,l])=><button key={v} className={filter===v?"is-active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div>}{loading&&<div className="portfolio-loading"><span></span><p>Cargando trabajos realizados…</p></div>}{!loading&&filtered.length>0&&<div className="portfolio-grid">{filtered.map(w=><article className="portfolio-card" key={w.id}><button type="button" className="portfolio-book portfolio-open" onClick={()=>open(w)}>{w.images[0]&&<figure className="portfolio-cover"><img src={w.images[0].url} alt={w.images[0].alt} loading="lazy"/></figure>}{w.images.length>1&&<span className="portfolio-photo-count">{w.images.length} fotos</span>}</button><div className="portfolio-copy"><div className="portfolio-meta"><span>{w.rubro==="electricidad"?"Electricidad":"Climatización"}</span>{w.localidad_publica&&<small>{w.localidad_publica}</small>}</div><h3>{w.titulo_publico}</h3><p>{w.resumen}</p><button className="inline-link" onClick={()=>open(w)}>Ver trabajo <span>→</span></button>{w.review&&<blockquote><span>{"★".repeat(w.review.puntuacion)}{"☆".repeat(5-w.review.puntuacion)}</span><p>“{w.review.comentario}”</p><cite>{w.review.nombre_publico}</cite></blockquote>}</div></article>)}</div>}{!loading&&filtered.length===0&&<div className="portfolio-empty"><span>MC</span><h3>Un book hecho con trabajos reales.</h3><p>Los trabajos publicados desde el panel aparecerán acá con sus fotografías y la experiencia verificada del cliente.</p></div>}{openWork&&<div className="portfolio-modal" role="dialog" aria-modal="true" onClick={()=>setOpenWork(null)}><div className="portfolio-modal-card" onClick={e=>e.stopPropagation()}><button className="portfolio-modal-close" onClick={()=>setOpenWork(null)}>×</button><div className="portfolio-modal-stage">{openWork.images[active]&&<img src={openWork.images[active].url} alt={openWork.images[active].alt}/>} {openWork.images.length>1&&<><button className="portfolio-prev" onClick={()=>move(-1)}>‹</button><button className="portfolio-next" onClick={()=>move(1)}>›</button><span className="portfolio-counter">{active+1} / {openWork.images.length}</span></>}</div>{openWork.images.length>1&&<div className="portfolio-thumbs">{openWork.images.map((i,n)=><button key={i.id} className={n===active?"is-active":""} onClick={()=>setActive(n)}><img src={i.url} alt=""/></button>)}</div>}<div className="portfolio-modal-copy"><span>{openWork.rubro==="electricidad"?"Electricidad":"Climatización"}</span><h2>{openWork.titulo_publico}</h2><p>{openWork.resumen}</p>{openWork.review&&<blockquote><b>{"★".repeat(openWork.review.puntuacion)}</b><p>“{openWork.review.comentario}”</p><cite>{openWork.review.nombre_publico}</cite></blockquote>}</div></div></div>}</>;
}