-- MetroClima · esquema inicial para Supabase
-- Ejecutar en un proyecto nuevo y luego crear exactamente dos usuarios en Auth.

create extension if not exists "pgcrypto";

create type public.rol_metroclima as enum ('administrador');
create type public.estado_consulta as enum ('pendiente', 'en_seguimiento', 'respondida', 'presupuestada', 'archivada');
create type public.estado_presupuesto as enum ('borrador', 'enviado', 'aceptado', 'rechazado', 'vencido');

create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  rol public.rol_metroclima not null default 'administrador',
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table public.consultas (
  id uuid primary key default gen_random_uuid(),
  categoria text not null,
  titulo text not null check (char_length(titulo) between 8 and 140),
  consulta text not null check (char_length(consulta) between 20 and 3000),
  nombre_publico text not null default 'Consulta anónima',
  acepta_contacto boolean not null default false,
  email text,
  telefono text,
  localidad text,
  estado public.estado_consulta not null default 'pendiente',
  visible_publicamente boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.respuestas (
  id uuid primary key default gen_random_uuid(),
  consulta_id uuid not null references public.consultas(id) on delete cascade,
  autor_id uuid not null references public.perfiles(id),
  respuesta text not null check (char_length(respuesta) between 3 and 5000),
  publica boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.clientes (
  id uuid primary key default gen_random_uuid(),
  tipo text not null default 'persona',
  nombre_razon_social text not null,
  cuit_dni text,
  condicion_iva text,
  email text,
  telefono text,
  direccion text,
  localidad text,
  observaciones text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.materiales (
  id uuid primary key default gen_random_uuid(),
  codigo text unique,
  nombre text not null,
  unidad text not null,
  costo_referencia numeric(14,2) not null default 0,
  controla_stock boolean not null default false,
  stock_actual numeric(14,3),
  stock_minimo numeric(14,3),
  activo boolean not null default true,
  actualizado_en timestamptz not null default now()
);

create table public.presupuestos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid references public.clientes(id),
  titulo text not null,
  descripcion text,
  tratamiento_fiscal text not null default 'monotributo_iva_no_discriminado',
  subtotal_mano_obra numeric(14,2) not null default 0,
  subtotal_materiales numeric(14,2) not null default 0,
  iva numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  validez_dias integer not null default 15,
  estado public.estado_presupuesto not null default 'borrador',
  creado_por uuid not null references public.perfiles(id),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.items_presupuesto (
  id uuid primary key default gen_random_uuid(),
  presupuesto_id uuid not null references public.presupuestos(id) on delete cascade,
  tipo text not null check (tipo in ('mano_obra', 'material')),
  descripcion text not null,
  cantidad numeric(14,3) not null default 1,
  precio_unitario numeric(14,2) not null default 0,
  total numeric(14,2) generated always as (cantidad * precio_unitario) stored,
  material_id uuid references public.materiales(id),
  orden integer not null default 0
);

create table public.comprobantes (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid references public.clientes(id),
  presupuesto_id uuid references public.presupuestos(id),
  responsable_id uuid not null references public.perfiles(id),
  tipo text not null default 'Factura C',
  punto_venta integer,
  numero bigint,
  cae text,
  cae_vencimiento date,
  total numeric(14,2) not null,
  estado text not null default 'borrador',
  respuesta_arca jsonb,
  emitido_en timestamptz,
  creado_en timestamptz not null default now()
);

create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.perfiles
    where id = auth.uid() and activo = true and rol = 'administrador'
  );
$$;

revoke all on function public.es_admin() from public;
grant execute on function public.es_admin() to authenticated;

alter table public.perfiles enable row level security;
alter table public.consultas enable row level security;
alter table public.respuestas enable row level security;
alter table public.clientes enable row level security;
alter table public.materiales enable row level security;
alter table public.presupuestos enable row level security;
alter table public.items_presupuesto enable row level security;
alter table public.comprobantes enable row level security;

create policy "publico puede crear consultas"
on public.consultas for insert
to anon, authenticated
with check (estado = 'pendiente');

create policy "administradores gestionan consultas"
on public.consultas for all
to authenticated
using (public.es_admin())
with check (public.es_admin());

create policy "publico ve respuestas publicas"
on public.respuestas for select
to anon, authenticated
using (publica = true);

create policy "administradores gestionan respuestas"
on public.respuestas for all
to authenticated
using (public.es_admin())
with check (public.es_admin());

create policy "usuario ve su perfil"
on public.perfiles for select
to authenticated
using (id = auth.uid());

create policy "administradores gestionan datos internos"
on public.perfiles for all
to authenticated
using (public.es_admin())
with check (public.es_admin());

create policy "administradores gestionan clientes"
on public.clientes for all to authenticated
using (public.es_admin()) with check (public.es_admin());

create policy "administradores gestionan materiales"
on public.materiales for all to authenticated
using (public.es_admin()) with check (public.es_admin());

create policy "administradores gestionan presupuestos"
on public.presupuestos for all to authenticated
using (public.es_admin()) with check (public.es_admin());

create policy "administradores gestionan items de presupuesto"
on public.items_presupuesto for all to authenticated
using (public.es_admin()) with check (public.es_admin());

create policy "administradores gestionan comprobantes"
on public.comprobantes for all to authenticated
using (public.es_admin()) with check (public.es_admin());

-- Vista pública deliberadamente limitada: no incluye correo, teléfono ni localidad.
create or replace view public.consultas_publicas
with (security_barrier = true)
as
select
  c.id,
  c.categoria,
  c.titulo,
  c.consulta,
  c.nombre_publico,
  c.creado_en,
  (
    select r.respuesta
    from public.respuestas r
    where r.consulta_id = c.id and r.publica = true
    order by r.creado_en desc
    limit 1
  ) as respuesta
from public.consultas c
where c.visible_publicamente = true
  and c.estado <> 'archivada';

revoke all on public.consultas_publicas from public;
grant select on public.consultas_publicas to anon, authenticated;

create index consultas_estado_creado_idx on public.consultas (estado, creado_en desc);
create index respuestas_consulta_idx on public.respuestas (consulta_id, creado_en desc);
create index presupuestos_cliente_idx on public.presupuestos (cliente_id, creado_en desc);
create index comprobantes_cliente_idx on public.comprobantes (cliente_id, creado_en desc);

-- Después de crear los dos usuarios desde Supabase Auth, vincularlos así:
-- insert into public.perfiles (id, nombre) values
--   ('UUID_DE_CRISTIAN', 'Cristian'),
--   ('UUID_DE_NICOLAS', 'Nicolás');
